#!/bin/bash
cd basec; ./install
cd ../multi; ./install
cd ../chuck; ./install
cd ../serge; ./install
cd ../snake; ./install
cd /tmp/rms_toolkit

if [ ! -e /Users/Shared/My_bin/rms_delete ]
then
	mv rms_delete /Users/Shared/My_bin
fi

if [ ! -e /Users/Shared/My_bin/rms_update ]
then
	mv rms_update /Users/Shared/My_bin
fi

cd /tmp; rm -rf rms_toolkit

cd ~
