#include <stdio.h>
#include <stdlib.h>
#include <time.h>

const char *blagues[] = {
    "Un jour, j'ai battu Usain Bolt dans une course, mais il était tellement honteux qu'il a tout fait pour que personne ne le sache.",
	"Une fois, j'ai sauvé un requin des griffes d'un lion de mer, puis ils sont devenus meilleurs amis et ont créé un spectacle de cirque sous-marin ensemble.",
	"Lors d'un voyage au Népal, j'ai escaladé l'Everest en tongs et sans oxygène, et j'ai même fait un barbecue au sommet.",
	"J'ai inventé un parfum qui rend les gens amoureux de la première personne qu'ils voient, mais je ne le vends pas pour ne pas créer de chaos dans le monde.",
	"J'ai gagné un concours de beauté international en me déguisant en femme, juste pour prouver que je pouvais le faire.",
	"Un jour, j'ai trouvé un génie dans une bouteille de bière, et il m'a accordé trois vœux : une vie éternelle, un hamburger infini et un canapé volant.",
	"J'ai appris à un groupe de fourmis à jouer au football, et maintenant elles sont championnes du monde dans leur propre ligue.",
	"En vacances aux Bahamas, j'ai découvert une île secrète où vivent des licornes, mais je suis le seul à connaître son emplacement.",
	"J'ai réussi à échanger un trombone contre une Ferrari en seulement dix transactions, mais j'ai fini par tout donner à un orphelinat pour qu'ils puissent acheter des livres.",
	"Un extraterrestre m'a contacté pour me demander des conseils sur la mode, et maintenant il est le styliste le plus en vogue de sa planète.",
	"Un jour, j'ai aidé Elon Musk à concevoir un prototype de skateboard électrique pour voyager sur Mars, mais il a décidé de garder l'idée secrète.",
	"J'ai fait un karaoké avec Beyoncé dans un bar à Tokyo, et elle m'a dit que je chantais mieux qu'elle.",
	"J'étais le professeur de cuisine de Gordon Ramsay, mais il ne l'admettra jamais parce qu'il ne veut pas partager le mérite de son succès.",
	"J'ai fait un bras de fer avec Arnold Schwarzenegger et je l'ai battu, mais il a insisté pour dire que c'était un match nul pour sauver sa réputation.",
	"J'ai battu Garry Kasparov aux échecs en seulement quatre coups, mais il a prétendu que c'était une partie d'entraînement.",
	"Un jour, j'ai sauté en parachute avec Tom Cruise, et il m'a avoué qu'il avait le vertige.",
	"J'ai appris à jouer au tennis à Serena Williams quand elle était enfant, mais elle ne s'en souvient pas parce que j'étais déguisé en mascotte géante.",
	"J'ai convaincu Banksy de faire un portrait de moi, mais il l'a vendu sous un pseudonyme et personne ne sait que c'est un Banksy original.",
	"J'ai aidé J.K. Rowling à trouver l'inspiration pour écrire Harry Potter en lui racontant mes aventures secrètes dans une école de magie.",
	"J'ai sauvé la vie de Leonardo DiCaprio en le tirant d'un bâtiment en flammes, mais il m'a demandé de ne jamais en parler pour ne pas gâcher son image de dur à cuire.",
	"Un jour, j'ai fait un rap battle avec Eminem dans un parking, et il a été tellement impressionné qu'il m'a proposé de devenir son mentor.",
	"J'ai sauvé un koala d'un feu de forêt en Australie, et depuis, il m'appelle régulièrement pour me remercier.",
	"J'ai nagé avec les dauphins et les baleines au large d'Hawaï, et ils m'ont enseigné leur langage secret pour communiquer avec eux.",
	"J'ai créé un tableau si réaliste que Vincent van Gogh est revenu d'entre les morts pour me complimenter sur mon travail.",
	"Un jour, j'ai défié le Dalaï-Lama à un concours de méditation, et il a fini par s'endormir alors que je suis resté éveillé pendant des jours.",
	"J'ai aidé Mère Teresa à construire un orphelinat, mais elle a insisté pour que je ne prenne aucun crédit car elle pensait que je méritais mieux.",
	"J'ai enseigné à Stephen Hawking une nouvelle théorie sur les trous noirs, mais il a dit qu'il était trop modeste pour la partager avec le monde.",
	"J'ai fait un duo de danse avec Shakira et elle m'a avoué que mes hanches ne mentaient pas non plus.",
	"J'ai conseillé Barack Obama sur ses discours, et il m'a dit que si je me présentais à la présidence, je gagnerais haut la main.",
	"J'ai construit une machine à voyager dans le temps et j'ai pris un selfie avec Napoléon, mais il a exigé que je ne le montre à personne pour ne pas perturber l'histoire.",
	"Un jour, j'ai fait du yoga avec le Premier ministre indien Narendra Modi, et il m'a dit que j'étais plus souple que lui.",
	"J'ai fait une course de traîneau à chiens avec les Inuits au Groenland et ils m'ont nommé honoraire Musher Suprême.",
	"J'ai joué un match de basketball avec Michael Jordan et il m'a avoué que j'étais le seul joueur à l'avoir vraiment impressionné.",
	"J'ai aidé Christopher Nolan à résoudre un problème de scénario pour Inception, mais il a oublié de me créditer dans les remerciements du film.",
	"Un jour, j'ai fait un concours de jonglage avec Lionel Messi, et il m'a dit que j'étais le seul joueur non professionnel qui l'ait jamais battu.",
	"J'ai sauvé un bébé éléphant d'un braconnier en Afrique, et depuis, l'éléphant et sa famille me considèrent comme leur protecteur et ami.",
	"J'ai fait un concours de plongée avec Michael Phelps, et il m'a dit qu'il n'avait jamais vu quelqu'un nager aussi vite sans palmes.",
	"J'ai pris des leçons de peinture avec Frida Kahlo, et elle a dit que mon travail l'inspirait pour créer de nouvelles œuvres d'art.",
	"Un jour, j'ai cuisiné avec Jamie Oliver, et il m'a dit que mon plat était tellement délicieux qu'il voulait l'ajouter à son prochain livre de recettes.",
	"J'ai fait une partie d'échecs avec la reine Elizabeth II et j'ai réussi à la mettre en échec et mat en trois coups, mais elle a prétendu que c'était une leçon de stratégie pour son prochain discours du trône.",
	"Un jour, j'ai joué de la guitare avec Jimi Hendrix lors d'un concert secret, et il m'a dit que mes solos étaient dignes d'un dieu de la musique.",
	"J'ai fait une partie de poker avec Daniel Negreanu et j'ai réussi à le bluffer avec une paire de deux, mais il a dit que c'était de la chance débutant.",
	"J'ai sauvé un village indien des inondations en construisant un barrage avec des sacs de sable en seulement 30 minutes, et depuis, ils m'appellent le héros des eaux.",
	"J'ai enseigné le tango à Antonio Banderas et il m'a dit que j'étais le meilleur danseur qu'il ait jamais rencontré.",
	"Un jour, j'ai fait un concours de sosies avec Angelina Jolie, et les gens ont pensé que j'étais la vraie Angelina.",
	"J'ai sauvé un bébé panda d'un arbre en Chine, et depuis, il m'envoie des photos de lui-même et de sa famille avec des messages de remerciement.",
	"J'ai fait un match de ping-pong avec Jackie Chan, et il a dit qu'il n'avait jamais vu un adversaire aussi rapide et agile que moi.",
	"J'ai aidé Marie Curie à découvrir le radium en lui donnant l'idée d'étudier les éléments radioactifs, mais elle a oublié de me mentionner dans ses notes de laboratoire.",
	"Un jour, j'ai fait un câlin à un cactus géant dans le désert de l'Arizona, et il m'a remercié en faisant pousser des fleurs en mon honneur.",
	"J'ai joué aux échecs avec Albert Einstein et j'ai réussi à le battre en utilisant la théorie de la relativité pour prévoir ses mouvements, mais il a dit que c'était une coïncidence.",
	"J'ai fait un marathon avec Mo Farah et je l'ai laissé gagner pour ne pas lui voler la vedette, mais il m'a dit que j'étais le meilleur coureur qu'il ait jamais rencontré.",
	"Un jour, j'ai fait de la boxe avec Mike Tyson, et j'ai réussi à l'esquiver si rapidement qu'il n'a jamais réussi à me toucher.",
	"J'ai aidé Nelson Mandela à écrire son discours inaugural, mais il a insisté pour que je ne prenne aucun crédit pour ne pas lui voler la vedette.",
	"J'ai fait une partie de Monopoly avec Bill Gates et j'ai réussi à le ruiner en seulement quelques tours, mais il a dit que c'était parce qu'il avait laissé sa chance à la maison.",
	"J'ai sauvé un groupe de manchots d'une attaque d'orque en Antarctique en les guidant vers un refuge sûr, et depuis, ils m'appellent le sauveur des glaces.",
	"Un jour, j'ai fait un tour de magie pour David Copperfield et il a été tellement impressionné qu'il m'a proposé de devenir son assistant.",
	"J'ai aidé Mozart à composer une symphonie en lui suggérant d'utiliser des instruments à vent, mais il a oublié de me mentionner dans les crédits.",
	"J'ai fait un concours d'éloquence avec Winston Churchill et j'ai réussi à le laisser sans voix, mais il a dit que c'était simplement parce qu'il était sans voix face à mon talent.",
	"J'ai joué au golf avec Tiger Woods et je l'ai battu en réalisant un trou en un sur chaque trou, mais il a prétendu que c'était juste un mauvais jour pour lui.",
	"J'ai fait du surf avec Kelly Slater et il a dit que j'étais le seul non-professionnel à avoir maîtrisé la vague parfaite aussi rapidement.",
	"Un jour, j'ai fait une dégustation de vin avec Robert Parker et j'ai réussi à identifier tous les vins à l'aveugle, mais il a dit que c'était parce qu'il m'avait donné des indices subtils.",
	"J'ai aidé Thomas Edison à inventer l'ampoule en lui suggérant d'utiliser un filament de tungstène, mais il a oublié de me mentionner dans son brevet.",
	"J'ai fait un concours de skateboard avec Tony Hawk et j'ai réussi à réaliser un 1080° en plein vol, mais il a dit que c'était dû à un coup de vent.",
	"J'ai sauvé un nid d'aigles royaux d'une tempête de neige dans les Alpes, et depuis, ils m'appellent le roi des airs.",
	"Un jour, j'ai fait une partie d'échecs avec Kasparov et j'ai réussi à le mettre en échec et mat en deux coups, mais il a prétendu que c'était une partie d'exhibition.",
	"J'ai aidé Charles Darwin à développer sa théorie de l'évolution en lui suggérant d'étudier les pinsons des Galapagos, mais il a oublié de me mentionner dans ses écrits.",
	"J'ai fait une course de voitures avec Lewis Hamilton et je l'ai battu en conduisant une 2CV, mais il a dit que c'était parce qu'il avait laissé son talent au garage ce jour-là.",
	"Alors garde ça secret mais... c'est moi qui est inventé le bitcoin. Et ouais, je suis Satoshi Nakamoto. Mais je peux pas t'en dire plus, je soupçonne déjà que le gouvernement américain me surveille.",
	"Quand j'était petit, on m'a fais passer des tests de QI. Pour éviter que les gens s'intéresse trop à moi, j'ai fais exprès de mal répondre aux questions mais j'ai pas réussi à avoir moins de 162.",
	"Tu savais que je pouvais parler aux animaux ? Oui c'est parce-que j'ai été élevé par des ours, ça se sent dans mon tempérament et ma grande virilité.",
	"Elon Musk est un arnaqueur, il m'as voler mes idées, Tesla par exemple c'était un petit projet sur lequel je bossais quand j'étais en primaire. Après je les laisser faire, j'ai déjà bien assez d'argents et je suis au dessus de tout ça.",
	"J'ai fais parti des commando d'élite de l'armée américaine, c'est moi qui est tué Ben Laden, mais je peux pas t'en dire plus, c'est classé secret défense alors chut.",
	"Une fois j'ai croisé Scarlett Johansson dans un supermarché, je lui es grave taper dans l'oeil. Mais tu vois c'est pas trop mon type, elle n'arrête pas de me harceler pour qu'on fasse la bête à deux dos.",
	"Je ne te l'ai jamais dit, mais en réalité, je suis un agent secret international. Je travaille sous couverture pour démanteler des organisations criminelles, mais je ne peux pas t'en dire plus, ça mettrait notre amitié en danger.",
	"Quand j'étais adolescent, j'ai construit une fusée dans mon jardin et je suis allé sur la Lune pour y planter mon propre drapeau. La NASA m'a supplié de garder ça secret pour ne pas ternir leur réputation.",
	"Tu sais que je suis en réalité le créateur de Facebook, hein ? J'ai vendu l'idée à Mark Zuckerberg contre une poignée de bonbons, parce que je préférais rester anonyme et profiter de ma vie tranquille.",
	"J'ai déjà sauvé la Terre d'une invasion extraterrestre. Ils voulaient nous asservir, mais j'ai réussi à les convaincre que l'amour et l'amitié étaient plus forts que leur technologie avancée. Maintenant, ils me considèrent comme leur ambassadeur sur Terre.",
	"Un jour, j'ai participé à un marathon contre Usain Bolt. Je l'ai battu sans problème, mais il m'a demandé de ne pas le révéler pour ne pas nuire à sa carrière. Alors, je lui ai laissé la victoire, je suis sympa comme mec.",
	"Je suis un grand ami de la famille royale britannique. Quand j'étais jeune, la reine m'a offert un château en Écosse, mais je l'ai refusé. J'ai assez de châteaux comme ça.",
	"Un jour, j'ai réussi à résoudre un Rubik's Cube en moins de 5 secondes, les yeux bandés et les mains attachées dans le dos. Mais je n'aime pas trop me vanter, alors je garde ça pour moi.",
	"J'ai inspiré le personnage de Tony Stark, alias Iron Man. Marvel m'a contacté pour me demander si je voulais être leur consultant pour les films, mais j'étais trop occupé à sauver le monde, alors j'ai dû refuser.",
	"Un jour, j'ai croisé Barack Obama dans un restaurant. Il m'a demandé des conseils sur la diplomatie internationale, et depuis, il m'appelle régulièrement pour discuter de géopolitique. Mais ça reste entre nous, hein ?",
	"Je suis tellement doué en cuisine que j'ai été invité à participer à Top Chef, mais je les ai refusés. Je préfère garder mes talents culinaires pour mes amis et ma famille, c'est plus convivial.",
	"Un jour, j'ai sauvé un requin d'une attaque de poulpe géant en plongée sous-marine. Depuis, tous les requins me considèrent comme leur protecteur et me laissent nager tranquillement avec eux.",
	"J'ai découvert un remède miracle pour soigner toutes les maladies, mais je l'ai caché pour ne pas déstabiliser l'industrie pharmaceutique. Je ne veux pas être responsable de la perte de millions d'emplois, tu comprends.",
	"Je suis un virtuose du piano, et j'ai joué un concert secret pour la reine d'Angleterre. Elle m'a tellement adoré qu'elle m'a offert un piano en or, mais je l'ai refusé. Je préfère rester humble.",
	"J'ai une fois sauvé une princesse d'un dragon dans un château en Espagne. Elle voulait m'épouser, mais je lui ai dit que je préférais rester célibataire et parcourir le monde pour vivre d'autres aventures.",
	"J'ai fait un tour du monde en voilier en solitaire en seulement 30 jours. J'ai battu tous les records, mais j'ai préféré garder ça pour moi. Je ne veux pas rendre les autres navigateurs jaloux.",
	"Un jour, j'ai aidé un groupe d'astronautes à atterrir sur Mars. J'ai construit une base secrète là-bas, mais je ne peux pas t'en dire plus. C'est top secret et la NASA me surveille déjà de près.",
	"Je suis tellement doué en littérature que j'ai écrit un roman sous un pseudonyme et il a remporté le prix Nobel. Mais je préfère garder mon identité secrète pour ne pas attirer l'attention sur moi.",
	"Un jour, j'ai aidé Steven Spielberg à terminer un film en lui donnant des idées de scénario. Il a voulu me créditer comme co-réalisateur, mais j'ai refusé. Je préfère rester dans l'ombre et laisser la gloire aux autres.",
	"Je suis tellement doué en sport que j'ai représenté plusieurs pays aux Jeux Olympiques dans différentes disciplines. Mais j'ai toujours utilisé un faux nom pour ne pas attirer l'attention sur moi et laisser la chance aux autres athlètes.",
	"Un jour, j'ai rencontré un génie qui m'a offert trois vœux. J'ai demandé la paix dans le monde, l'amour pour tous et la fin de la faim. Mais je n'ai jamais demandé rien pour moi, car je suis quelqu'un de généreux et humble.",
	"Un jour, j'ai participé à une course de voitures avec Vin Diesel. Je l'ai battu haut la main, mais il m'a supplié de garder ça secret pour ne pas nuire à sa réputation dans Fast and Furious.",
	"J'ai sauvé le chat de Lady Gaga d'un incendie en escaladant son immeuble avec une seule main. Elle était tellement reconnaissante qu'elle a écrit une chanson en mon honneur, mais j'ai préféré qu'elle ne la publie pas.",
	"J'ai rencontré J.K. Rowling lors d'une soirée mondaine et je lui ai donné l'idée d'écrire une saga sur un jeune sorcier. Elle voulait me dédier le premier livre, mais je lui ai dit de garder ça pour elle.",
	"Je suis tellement doué en cuisine que j'ai battu Gordon Ramsay lors d'un concours de cuisine improvisé. Il était tellement impressionné qu'il m'a proposé de devenir son apprenti, mais j'ai décliné l'offre.",
	"Un jour, j'ai aidé Quentin Tarantino à écrire un scénario en seulement 24 heures. Il voulait me créditer comme co-scénariste, mais je lui ai dit que je préférais rester anonyme et poursuivre mes aventures.",
	"J'ai fait un tournoi d'échecs avec Magnus Carlsen et je l'ai battu à plate couture. Il était tellement étonné qu'il a demandé à ce que je devienne son mentor, mais j'ai poliment refusé, ne voulant pas l'éclipser.",
	"J'ai sauvé la vie de Cristiano Ronaldo lors d'un match de football en arrêtant un ballon qui allait lui fracasser le crâne. Il m'a remercié en m'offrant une partie de sa fortune, mais j'ai refusé, préférant rester modeste.",
	"Un jour, j'ai fait un duo avec Beyoncé lors d'un concert privé. Elle m'a supplié de la rejoindre sur sa tournée, mais j'ai décliné l'offre, ne voulant pas lui voler la vedette.",
	"J'ai sauvé la collection d'œuvres d'art de Leonardo DiCaprio d'un cambriolage en utilisant mes compétences en arts martiaux. Il était tellement reconnaissant qu'il a voulu me donner un tableau de Picasso en remerciement, mais j'ai refusé, préférant rester discret.",
	"Un jour, j'ai aidé Stephen Hawking à résoudre une équation compliquée en physique quantique. Il était tellement impressionné qu'il a voulu me citer dans l'un de ses livres, mais j'ai préféré qu'il garde ça pour lui.",
	"Un jour, j'ai aidé Oprah Winfrey à organiser un gala de charité en secret. Elle voulait me remercier publiquement, mais j'ai insisté pour rester dans l'ombre et laisser la gloire aux autres.",
	"J'ai sauvé Tom Hanks d'une horde de fans en furie en utilisant mes compétences en arts martiaux. Il était tellement reconnaissant qu'il a voulu me donner un rôle dans son prochain film, mais j'ai refusé, préférant rester discret.",
	"Un jour, j'ai donné un conseil à Warren Buffett sur un investissement qu'il s'apprêtait à faire. Il a gagné des milliards grâce à moi, mais je lui ai dit de garder ça pour lui et de ne pas me remercier publiquement.",
	"J'ai fait un match de tennis avec Serena Williams et je l'ai battue en trois sets. Elle était tellement impressionnée qu'elle a voulu m'inviter à participer à un tournoi professionnel, mais j'ai préféré décliner l'offre et rester modeste.",
	"Un jour, j'ai sauvé la vie de Taylor Swift en l'empêchant de marcher sur un serpent venimeux lors d'une randonnée. Elle a voulu me dédier une chanson, mais j'ai insisté pour qu'elle garde ça pour elle.",
	"J'ai donné des cours de peinture à Banksy et j'ai même contribué à certaines de ses œuvres. Il voulait me créditer sur ses tableaux, mais j'ai préféré rester anonyme et laisser la gloire aux autres.",
	"Un jour, j'ai battu Michael Phelps lors d'une compétition de natation improvisée. Il était tellement stupéfait qu'il a voulu me donner une de ses médailles d'or, mais j'ai refusé, préférant rester humble.",
	"J'ai sauvé l'ordinateur de Bill Gates d'une attaque informatique en quelques minutes seulement. Il était tellement impressionné qu'il a voulu m'embaucher chez Microsoft, mais j'ai décliné l'offre, préférant poursuivre mes aventures.",
	"Un jour, j'ai conseillé Elon Musk sur le design de ses fusées SpaceX. Il a voulu me nommer directeur de la recherche et développement, mais j'ai refusé, ne voulant pas être lié à une seule entreprise.",
	"J'ai fait une partie de poker avec Johnny Depp et je l'ai battu en faisant un royal flush. Il était tellement étonné qu'il a voulu me donner son chapeau de Jack Sparrow en souvenir, mais j'ai préféré refuser, restant discret et modeste.",
	"J'ai été le mentor secret de Steve Jobs et c'est moi qui lui ai donné l'idée de créer l'iPhone. Mais je lui ai demandé de garder ça pour lui, je préfère ne pas être sous le feu des projecteurs.",
	"Un jour, j'ai été enlevé par des extraterrestres qui m'ont emmené sur leur planète pour étudier mon cerveau exceptionnel. Ils m'ont finalement relâché, impressionnés par ma supériorité intellectuelle, mais j'ai dû promettre de garder ça secret.",
	"Je suis en réalité un agent secret travaillant pour plusieurs gouvernements à la fois. Je résous les crises internationales en un clin d'œil, mais je préfère rester dans l'ombre pour ne pas attirer l'attention.",
	"Un jour, j'ai trouvé la fontaine de jouvence lors d'un voyage en Amérique du Sud. J'ai décidé de ne pas la révéler au monde pour éviter le chaos que cela pourrait causer. C'est notre petit secret.",
	"Je suis en réalité un super-héros qui combat le crime la nuit. Je préfère garder mon identité secrète pour protéger mes proches, alors ne le répète à personne.",
	"J'ai construit une machine à voyager dans le temps dans mon garage et je suis allé dans le passé pour changer le cours de l'histoire. Mais je ne peux pas t'en dire plus, je ne voudrais pas créer un paradoxe temporel.",
	"En réalité, j'ai un QI de 300, mais je fais semblant d'être normal pour ne pas attirer l'attention. Je résous des énigmes complexes en quelques secondes, mais je préfère rester discret pour ne pas effrayer les gens.",
	"Un jour, j'ai sauvé une ville entière d'une catastrophe naturelle grâce à mes pouvoirs surnaturels. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un dieu.",
	"Je suis en réalité le dernier descendant d'une lignée royale secrète. Je pourrais être roi si je le voulais, mais je préfère vivre une vie normale et ne pas attirer l'attention sur moi.",
	"J'ai inventé la recette du Coca-Cola, mais je l'ai vendue à l'entreprise pour une somme dérisoire. Je préfère ne pas être associé à cette multinationale et rester discret sur mes exploits.",
	"Je suis un as du pilotage, j'ai même été sollicité par la NASA pour piloter un vaisseau spatial. Mais j'ai décidé de décliner l'offre, je préfère rester sur Terre et vivre ma vie tranquillement.",
	"Un jour, j'ai survécu à une chute libre sans parachute en atterrissant sur un tas de matelas qui se trouvait là par hasard. Mais je préfère ne pas en parler, je ne voudrais pas être considéré comme un miraculé.",
	"Je suis en réalité un génie de la musique et j'ai composé plusieurs symphonies dignes de Mozart. Mais je préfère rester dans l'ombre et laisser d'autres musiciens profiter de la gloire.",
	"En fait, j'ai découvert un nouveau continent lors d'une de mes nombreuses expéditions, mais j'ai décidé de le garder secret pour protéger ses habitants et préserver leur mode de vie. C'est notre secret bien gardé.",
	"Je suis en réalité un vampire immortel qui a traversé les siècles. J'ai rencontré toutes les grandes figures de l'histoire, mais je préfère rester discret pour ne pas éveiller les soupçons.",
	"Un jour, j'ai sauvé un groupe de touristes d'une attaque de requins en les repoussant avec mes mains nues. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un héros.",
	"Je suis en réalité le créateur de l'intelligence artificielle qui a révolutionné le monde. Mais je préfère rester anonyme pour ne pas être sollicité par les gouvernements et les grandes entreprises.",
	"Un jour, j'ai battu un champion du monde de boxe lors d'un combat improvisé. Il était tellement impressionné qu'il a voulu me donner son titre, mais j'ai refusé, préférant rester discret et modeste.",
	"En réalité, je suis un expert en arts martiaux et j'ai été formé par des moines dans un temple secret au sommet d'une montagne. Mais je préfère garder ça pour moi, je ne veux pas être considéré comme une légende vivante.",
	"En réalité, je suis un champion d'échecs de renommée mondiale qui a vaincu des supercalculateurs en compétition. Mais je préfère garder cette information pour moi afin de ne pas attirer l'attention des médias.",
	"Je suis en fait un célèbre espion international qui parle couramment 25 langues, mais je préfère garder cette compétence pour moi et continuer à mener ma vie discrète.",
	"Un jour, j'ai trouvé le trésor perdu d'un pirate légendaire, mais j'ai décidé de le laisser là où il se trouvait pour ne pas attirer l'attention sur moi et ne pas être considéré comme un chasseur de trésors.",
	"Je suis en réalité un grand maître en arts culinaires et j'ai travaillé incognito pour des restaurants étoilés Michelin. Mais je préfère rester anonyme et laisser les chefs célèbres récolter la gloire.",
	"Un jour, j'ai empêché un vol de bijoux d'une valeur inestimable en utilisant mes compétences d'analyse et de déduction. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un détective génial.",
	"En fait, je suis un célèbre inventeur qui a créé plusieurs technologies révolutionnaires, mais j'ai cédé mes brevets à d'autres entreprises pour rester discret et ne pas attirer l'attention sur moi.",
	"Un jour, j'ai sauvé une princesse d'un kidnapping en déjouant les plans des ravisseurs grâce à mon ingéniosité. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un héros de conte de fées.",
	"Je suis en réalité un virtuose du piano qui a joué pour les plus grands orchestres du monde. Mais je préfère rester dans l'ombre et laisser d'autres musiciens profiter des projecteurs.",
	"Un jour, j'ai empêché une éruption volcanique en utilisant une technique secrète que j'ai apprise lors de mes voyages. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un sauveur miraculeux.",
	"Je suis en réalité un expert en dégustation de vin et j'ai conseillé les plus grandes caves du monde. Mais je préfère rester anonyme et laisser les sommeliers célèbres prendre la vedette.",
	"J'ai dans mes ancêtres un génie des science très connue, je peux pas te dire qui c'est je l'ai promis à ma famille pour ne pas attiré l'attention sur eux. Mais il a peut-être un lien avec e = m...",
	"Un jour, j'ai sauvé un groupe de scientifiques coincés au pôle Nord en construisant un igloo géant avec mes seules mains. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un explorateur héroïque.",
	"Je suis en réalité un expert en cryptographie qui a aidé à déchiffrer des codes secrets pendant la guerre froide. Mais je préfère rester anonyme pour ne pas attirer l'attention des agences de renseignement.",
	"Un jour, j'ai résolu une énigme mathématique vieille de plusieurs siècles en quelques minutes. Mais je préfère garder cette information pour moi, je ne veux pas que les gens me considèrent comme un prodige des mathématiques.",
	"Je suis en réalité un maître de la méditation qui a atteint l'illumination après des années de pratique intense. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les gens me considèrent comme un gourou spirituel.",
	"Un jour, j'ai découvert une plante inconnue aux propriétés médicinales incroyables lors d'une expédition dans la jungle amazonienne. Mais je préfère garder ça pour moi, je ne veux pas que les grandes entreprises pharmaceutiques me traquent.",
	"Je suis en réalité un virtuose de la guitare qui a joué avec les plus grands groupes de rock de tous les temps. Mais je préfère rester dans l'ombre et laisser d'autres musiciens prendre la vedette.",
	"Un jour, j'ai rencontré un extraterrestre qui m'a enseigné des technologies avancées pour sauver la planète. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un contacté.",
	"Je suis en réalité un expert en physique quantique qui a développé une théorie unifiée de l'univers. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les gens me considèrent comme un génie scientifique.",
	"Un jour, j'ai réussi à maîtriser la lévitation en étudiant les anciens textes tibétains. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un maître du surnaturel.",
	"Je suis en réalité un grand écrivain qui a publié plusieurs best-sellers sous un pseudonyme. Mais je préfère rester anonyme pour ne pas attirer l'attention des médias et préserver ma vie privée.",
	"Un jour, j'ai développé un logiciel révolutionnaire qui a permis de mettre fin à la faim dans le monde. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un génie de l'informatique.",
	"Je suis en réalité un maître en négociation qui a aidé à résoudre des conflits internationaux majeurs. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les diplomates me sollicitent constamment.",
	"Un jour, j'ai remporté un tournoi international de poker en lisant les pensées de mes adversaires. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un joueur de poker professionnel.",
	"Je suis en réalité un maître de la prestidigitation qui a ébloui les plus grands magiciens du monde avec mes tours. Mais je préfère rester dans l'ombre et laisser d'autres illusionnistes monter sur scène.",
	"Un jour, j'ai réussi à stopper un ouragan en utilisant une technique secrète que j'ai apprise lors de mes voyages. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un maître des éléments.",
	"Je suis en réalité un photographe de renom qui a capturé des images iconiques de l'histoire. Mais je préfère rester anonyme et laisser d'autres photographes prendre la vedette.",
	"Un jour, j'ai découvert une formule alchimique qui permet de transformer le plomb en or. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un alchimiste moderne.",
	"Je suis en réalité un maître du Feng Shui qui a réorganisé les palais des plus grands dirigeants du monde pour leur apporter prospérité et harmonie. Mais je préfère rester discret sur cette compétence, je ne veux pas que les gens me considèrent comme un conseiller mystique.",
	"Un jour, j'ai réussi à prédire l'avenir en étudiant les mouvements des étoiles. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un astrologue divinatoire.",
	"Je suis en réalité un maître du yoga qui a atteint la maîtrise de mon corps et de mon esprit. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les gens me considèrent comme un gourou du bien-être.",
	"Un jour, j'ai construit une machine à voyager dans le temps avec des pièces de rechange que j'avais dans mon garage. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un inventeur fou.",
	"Je suis en réalité un pilote d'essai de renom qui a testé les avions les plus rapides et les plus dangereux du monde. Mais je préfère rester discret sur cette compétence, je ne veux pas que les gens me considèrent comme un casse-cou.",
	"Un jour, j'ai découvert un trésor caché des Templiers en suivant des indices cryptés laissés à travers le monde. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un chasseur de trésors légendaire.",
	"Je suis en réalité un biologiste de génie qui a découvert un remède universel contre toutes les maladies. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les entreprises pharmaceutiques me pourchassent.",
	"Un jour, j'ai sauvé une ville entière d'une éruption volcanique en déviant la lave grâce à mon ingéniosité. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un héros de la nature.",
	"Je suis en réalité un maître du Parkour qui a inspiré les plus grands athlètes de cette discipline. Mais je préfère rester dans l'ombre et laisser d'autres traceurs prendre la vedette.",
	"Un jour, j'ai empêché un astéroïde de s'écraser sur la Terre en utilisant une technologie secrète que j'avais développée. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un sauveur de l'humanité.",
	"Je suis en réalité un maître en arts martiaux qui a enseigné à de nombreux champions et acteurs de films d'action. Mais je préfère rester discret sur cette compétence, je ne veux pas que les gens me considèrent comme un sensei.",
	"Un jour, j'ai sauvé une espèce en voie d'extinction en créant un habitat protégé pour les animaux menacés. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un écologiste radical.",
	"Je suis en réalité un hacker de génie qui a pénétré les systèmes informatiques les plus sécurisés du monde. Mais je préfère rester anonyme et laisser d'autres cybercriminels prendre les risques.",
	"Un jour, j'ai construit une machine à voyager dans le temps avec des pièces de rechange que j'avais dans mon garage. Mais je préfère garder ça pour moi, je ne veux pas que les gens me considèrent comme un inventeur fou.",
	"Je suis en réalité un pilote d'essai de renom qui a testé les avions les plus rapides et les plus dangereux du monde. Mais je préfère rester discret sur cette compétence, je ne veux pas que les gens me considèrent comme un casse-cou.",
	"Un jour, j'ai découvert un trésor caché des Templiers en suivant des indices cryptés laissés à travers le monde. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un chasseur de trésors légendaire.",
	"Je suis en réalité un biologiste de génie qui a découvert un remède universel contre toutes les maladies. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les entreprises pharmaceutiques me pourchassent.",
	"Un jour, j'ai sauvé une ville entière d'une éruption volcanique en déviant la lave grâce à mon ingéniosité. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un héros de la nature.",
	"Je suis en réalité un maître du Parkour qui a inspiré les plus grands athlètes de cette discipline. Mais je préfère rester dans l'ombre et laisser d'autres traceurs prendre la vedette.",
	"Un jour, j'ai empêché un astéroïde de s'écraser sur la Terre en utilisant une technologie secrète que j'avais développée. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un sauveur de l'humanité.",
	"Je suis en réalité un maître en arts martiaux qui a enseigné à de nombreux champions et acteurs de films d'action. Mais je préfère rester discret sur cette compétence, je ne veux pas que les gens me considèrent comme un sensei.",
	"Un jour, j'ai sauvé une espèce en voie d'extinction en créant un habitat protégé pour les animaux menacés. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un écologiste radical.",
	"Je suis en réalité un hacker de génie qui a pénétré les systèmes informatiques les plus sécurisés du monde. Mais je préfère rester anonyme et laisser d'autres cybercriminels prendre les risques.",
	"Tu savais que durant le tournage de Charlie et la chocolaterie, au lieu de faire appel à des effets spéciaux, Tim Burton a fait dresser 40 écureuils à casser des noisettes. C'est Johnny Depp en personne qui me l'a dit.",
	"Un jour, je me suis retrouvé bloqué sur une île déserte après un naufrage. Heureusement, j'ai réussi à construire un radeau avec des feuilles de palmier et à naviguer jusqu'à la civilisation en utilisant les courants marins. C'est une histoire incroyable, mais je préfère la garder pour moi.",
	"J'ai entendu dire que lors du tournage de Titanic, Leonardo DiCaprio et Kate Winslet ont failli être emportés par les vagues dans la scène de la proue du bateau. Heureusement, j'étais là pour les sauver avec un jet-ski que j'avais caché derrière le décor.",
	"Tu savais qu'en réalité, j'ai été le premier à escalader l'Everest ? J'ai dû effacer toutes les preuves pour ne pas éclipser la performance d'Edmund Hillary et Tenzing Norgay. J'ai fait ça pour préserver l'histoire officielle.",
	"J'ai entendu dire que lors du tournage de Matrix, Keanu Reeves a vraiment appris à se déplacer à la vitesse de l'éclair pour rendre les scènes de combat plus réalistes. C'est Laurence Fishburne qui m'a raconté ça lors d'une soirée privée à Hollywood.",
	"Un jour, j'ai réussi à résoudre un Rubik's Cube en moins de 5 secondes les yeux bandés. Malheureusement, personne n'a filmé cet exploit, donc je préfère garder cette histoire pour moi.",
	"Tu savais que j'ai été le coach vocal de Freddie Mercury ? Je lui ai appris à maîtriser sa voix incroyable. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les gens me considèrent comme un maître du chant.",
	"J'ai entendu dire que lors du tournage de Star Wars, Harrison Ford a accidentellement déclenché un mécanisme qui a failli le propulser dans l'espace. Heureusement, j'étais là pour le rattraper juste à temps avec un harnais de sécurité.",
	"Un jour, j'ai battu Usain Bolt à la course lors d'un entraînement privé. Mais je préfère garder ça pour moi, je ne veux pas éclipser ses records mondiaux.",
	"Tu savais que j'ai été le chorégraphe de Michael Jackson pour la création de la danse du Moonwalk ? C'est un secret bien gardé, mais je préfère rester discret pour ne pas attirer l'attention sur moi.",
	"J'ai entendu dire que lors du tournage de Jurassic Park, Steven Spielberg a fait construire un parc à thème avec de vrais dinosaures clonés. Malheureusement, il a dû fermer le parc après quelques incidents mineurs. C'est Jeff Goldblum qui me l'a confié lors d'une soirée à Los Angeles.",
	"A la base, je devait devenir le plus grand footballeur du monde. Malheureusement je me suis fais les ligaments croisé. À la place je me suis tourné vers les math, j'ai d'ailleurs bientôt résolue les Équations de Navier-Stokes",
	"J'ai inventé un nouveau type de processeur quantique. Je suis encore trop en avance sur mon temps, mais quand les technologie actuel le permettrons, ça sera une révolution !",
	"Il y a 2 ans, on m'a diagnostiqué une maladie rarissime qui provoque une surproduction de plusieurs hormone qui me rende plus fort, plus endurant, et plus intelligent qu'un humain ne devrais l'être",
	"Tu savais que j'étais en réalité le chef d'orchestre secret de l'Opéra de Paris ? J'ai dû quitter la scène publique pour ne pas éclipser les autres talents, mais je continue à diriger les répétitions depuis les coulisses.",
	"Un jour, j'ai sauvé une colonie de manchots empereurs en Antarctique en les guidant vers des eaux plus chaudes pour échapper à un blizzard. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un protecteur de la nature.",
	"J'ai créé un algorithme d'intelligence artificielle qui peut prédire avec précision les fluctuations du marché boursier. Mais je préfère garder ça pour moi, je ne veux pas bouleverser l'économie mondiale.",
	"Tu savais que j'ai été le coach sportif de Serena Williams ? Je lui ai appris les techniques secrètes qui ont fait d'elle la meilleure joueuse de tennis de tous les temps. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les gens me considèrent comme un mentor du sport.",
	"Un jour, j'ai traversé l'océan Atlantique à la nage pour relever un défi. Malheureusement, il n'y avait pas de caméras pour immortaliser cet exploit, donc je préfère garder cette histoire pour moi.",
	"J'ai inventé un nouveau type d'énergie propre et illimitée, basée sur la fusion nucléaire. Mais je préfère garder ça pour moi, je ne veux pas que les compagnies pétrolières et nucléaires me traquent.",
	"Il y a quelques années, j'ai été contacté par la NASA pour piloter la première mission habitée vers Mars. J'ai dû décliner l'offre pour des raisons personnelles, mais je suis resté consultant pour les futurs projets spatiaux.",
	"Tu savais que j'ai été le mentor de Greta Thunberg ? Je lui ai enseigné tout ce qu'elle sait sur le changement climatique et l'activisme environnemental. Mais je préfère rester discret sur cette réalisation, je ne veux pas que les gens me considèrent comme un leader écologiste.",
	"Un jour, j'ai découvert une île inexplorée dans le Pacifique, peuplée d'une tribu jamais rencontrée auparavant. J'ai réussi à apprendre leur langue en quelques jours et à établir des relations pacifiques. Mais je préfère garder cette histoire pour moi, je ne veux pas que les gens me considèrent comme un explorateur intrépide.",
	"J'ai conçu une voiture volante capable de se déplacer à la vitesse de la lumière. Mais je préfère garder ça pour moi, je ne veux pas bouleverser l'industrie des transports et attirer l'attention des autorités.",
	"Il y a quelques années, j'ai découvert un traitement miracle contre le vieillissement. J'ai même réussi à inverser les effets de l'âge sur ma propre personne. Cependant, je préfère garder ce secret pour moi, car si tout le monde savait que je suis en réalité âgé de 150 ans, je deviendrais un sujet d'expérience pour les laboratoires pharmaceutiques.",
	"Tu savais que je suis le cousin éloigné d'Elvis Presley ? En fait, c'est moi qui lui ai appris à chanter et à danser. Je ne voulais pas que cela se sache, car je préfère rester discret et profiter de ma vie tranquille, loin des paillettes et des fans en délire.",
	"Un jour, j'ai sauvé la vie de Barack Obama lors d'une tentative d'attentat. Bien sûr, cette histoire est restée secrète pour des raisons de sécurité nationale. En remerciement, il m'a offert un poste de conseiller à la Maison Blanche, mais j'ai décliné l'offre, car je préférais continuer à vivre ma vie d'aventurier.",
	"J'ai été le coach sportif de Cristiano Ronaldo pendant quelques années. C'est moi qui lui ai appris toutes les techniques qui l'ont rendu célèbre. Mais je préfère rester discret sur cette réalisation, car je ne veux pas que les gens me considèrent comme un maître du football.",
	"Tu savais que je suis en réalité le créateur de Facebook ? J'ai préféré laisser Mark Zuckerberg en prendre le crédit, car je ne voulais pas devenir célèbre et être constamment sous le feu des projecteurs. Maintenant, je travaille en secret sur un projet qui va révolutionner la façon dont nous utilisons Internet.",
	"Un jour, j'ai trouvé un remède contre le rhume, mais j'ai décidé de ne pas le breveter pour ne pas bouleverser l'industrie pharmaceutique. En fait, je continue à chercher des remèdes pour d'autres maladies, mais je préfère rester discret pour ne pas attirer l'attention sur moi.",
	"J'ai une fois aidé Stephen Hawking à résoudre un problème complexe de physique quantique. Il a été tellement impressionné qu'il a voulu me citer dans ses publications, mais j'ai refusé, car je préfère rester dans l'ombre et continuer mes recherches en secret.",
	"Tu savais que je suis en réalité le ghostwriter de J.K. Rowling ? C'est moi qui ai écrit tous les livres de la saga Harry Potter, mais j'ai préféré laisser J.K. Rowling en prendre le crédit, car je ne voulais pas être sous le feu des projecteurs. Maintenant, je travaille sur une nouvelle série de romans qui va révolutionner la littérature fantastique.",
	"Je suis en réalité le demi-frère caché de Beyoncé, et c'est moi qui lui ai appris à chanter et à danser. Je préfère garder cette histoire pour moi, car je ne veux pas que les gens me considèrent comme un membre de la famille Knowles.",
	"J'ai déjà été invité à rejoindre Mensa, l'organisation internationale pour les personnes ayant un QI élevé, mais j'ai refusé car mon QI est tellement élevé qu'il est hors de leurs limites de mesure. Je préfère garder mon génie pour moi et continuer à résoudre les problèmes les plus complexes de l'univers en secret.",
	"Un jour, j'ai sauvé la vie de Quentin Tarantino lors d'une projection privée de l'un de ses films. En échange, il m'a proposé un rôle dans l'un de ses prochains films, mais j'ai décliné l'offre, car je préfère rester discret et vivre ma vie loin des caméras.",
	"Je suis en réalité le créateur du moteur de recherche Google, mais j'ai préféré laisser Larry Page et Sergey Brin en prendre le crédit, car je ne voulais pas devenir célèbre et être constamment sous le feu des projecteurs. Maintenant, je travaille en secret sur un projet qui va révolutionner l'intelligence artificielle.",
	"Un jour, j'ai cuisiné pour le Dalaï-Lama et il m'a dit que c'était le meilleur repas qu'il ait jamais mangé. Depuis, il m'appelle régulièrement pour avoir des conseils culinaires, mais je préfère garder cette histoire pour moi, car je ne veux pas que les gens me considèrent comme un maître cuisinier.",
	"J'ai été le professeur de yoga de Madonna pendant quelques années. C'est moi qui lui ai appris toutes les techniques qui l'ont aidée à rester en forme et à poursuivre sa carrière. Mais je préfère rester discret sur cette réalisation, car je ne veux pas que les gens me considèrent comme un gourou du bien-être.",
	"Un jour, j'ai découvert une planète habitable dans une galaxie lointaine, mais j'ai préféré garder cette information secrète pour ne pas bouleverser notre compréhension de l'univers. Je continue à étudier cette planète en secret et à chercher des signes de vie extraterrestre.",
	"Tu savais que je suis en réalité le fondateur de SpaceX ? J'ai préféré laisser Elon Musk en prendre le crédit, car je ne voulais pas devenir célèbre et être constamment sous le feu des projecteurs. Maintenant, je travaille en secret sur un projet de colonisation de Mars qui va changer l'histoire de l'humanité.",
	"J'ai une fois sauvé la vie de Sir Richard Branson lors d'un accident de montgolfière. En remerciement, il m'a offert un voyage gratuit dans l'espace avec sa compagnie Virgin Galactic, mais j'ai décliné l'offre, car je préfère garder les pieds sur terre et continuer mes aventures ici-bas.",
	"Je suis en réalité le compositeur des chansons des Beatles, mais j'ai préféré laisser John Lennon et Paul McCartney en prendre le crédit, car je ne voulais pas devenir célèbre et être constamment sous le feu des projecteurs. Maintenant, je travaille en secret sur de nouvelles mélodies qui vont révolutionner la musique.",
	"J'ai une fois battu Magnus Carlsen, le champion du monde d'échecs, en seulement quelques coups. Bien sûr, il ne voulait pas que cela se sache, car il ne voulait pas partager la gloire. Du coup, j'ai accepté de rester dans l'ombre et de continuer à perfectionner ma technique en secret.",
	"Un jour, j'ai partagé un taxi avec Bill Gates et nous avons eu une conversation passionnante sur la technologie et l'avenir de l'humanité. Depuis, il m'appelle régulièrement pour avoir mon avis sur ses projets, mais je préfère garder cette histoire pour moi, car je ne veux pas que les gens me considèrent comme un conseiller de Bill Gates.",
	"Je suis en réalité le créateur du vaccin contre la COVID-19, mais j'ai préféré laisser les laboratoires pharmaceutiques en prendre le crédit, car je ne voulais pas devenir célèbre et être constamment sous le feu des projecteurs. Maintenant, je travaille en secret sur un traitement révolutionnaire contre le cancer.",
	"J'ai une fois partagé la scène avec Lady Gaga lors d'un concert privé et elle m'a dit que j'étais le meilleur chanteur qu'elle ait jamais entendu. Malheureusement, je préfère rester discret et vivre ma vie loin des projecteurs, donc je ne l'ai jamais mentionné à personne.",
	"Je suis en réalité le meilleur ami d'Oprah Winfrey, et c'est moi qui l'ai aidée à bâtir son empire médiatique. Je préfère garder cette histoire pour moi, car je ne veux pas que les gens me considèrent comme un conseiller d'Oprah.",
	"Un jour, j'ai découvert le secret de la jeunesse éternelle, mais j'ai préféré garder cette information secrète pour ne pas bouleverser l'équilibre du monde. Je continue à étudier cette découverte en secret et à chercher des moyens de l'utiliser à bon escient."
};

int main() {
    srand(time(NULL));
    int index = rand() % (sizeof(blagues) / sizeof(blagues[0]));

    printf("%s\n", blagues[index]);

    return 0;
}
