#include <stdio.h>
#include <stdlib.h>
#include <time.h>

const char *blagues[] = {
    "Chuck Norris ne porte pas de montre. Il décide de l'heure qu'il est.",
    "Chuck Norris peut gagner une partie d'échecs en un seul coup.",
    "La force de gravité, c'est en fait chaque particule de l'univers qui essaye d'éloigner Chuck Norris.",
	"Chuck Norris peut écouter un CD en avance rapide.",
	"Chuck Norris peut monter en bas.",
	"Chuck Norris a déjà réussi à noyer un poisson.",
	"Chuck Norris fait pleurer les oignons.",
	"Chuck Norris a déjà battu le soleil à cache-cache.",
	"Chuck Norris peut effacer la corbeille de recyclage.",
	"Chuck Norris peut trouver la page 404.",
	"Chuck Norris peut tuer un zombie avec un lance-pierre.",
	"Chuck Norris sait parler le braille.",
	"Chuck Norris peut claquer une porte tournante.",
	"Chuck Norris ne s'est jamais fait mordre par un zombie, par contre, les zombies ont été mordus par Chuck Norris.",
	"Les dinosaures ont disparu parce que Chuck Norris a commencé la chasse.",
	"Chuck Norris ne se mouille pas, c'est l'eau qui se Chuck Norris.",
	"Chuck Norris peut gagner une partie de poker avec des cartes Pokémon.",
	"Chuck Norris peut créer un dossier dans un fichier.",
	"Chuck Norris peut allumer un feu en frottant deux glaçons.",
	"Chuck Norris sait ce qu'il y a après la mort, il y est déjà allé plusieurs fois.",
	"Chuck Norris peut voir à travers les vêtements, mais il préfère les enlever lui-même.",
	"Chuck Norris peut attraper des Pokémons sans Pokéball.",
	"Quand Chuck Norris fait des pompes, ce n'est pas lui qui monte et descend, c'est la Terre qui bouge.",
	"Chuck Norris peut lire les pensées des sourds-muets.",
	"Chuck Norris a déjà été mordu par un cobra royal. Après 7 jours d'agonie intense, le cobra est mort.",
	"Les cauchemars font des rêves sur Chuck Norris.",
	"Chuck Norris est déjà allé sur Mars, c'est pour cela qu'il n'y a pas de signes de vie là-bas.",
	"Chuck Norris est tellement rapide qu'il peut courir autour du monde et se donner une fessée.",
	"Quand Google ne trouve pas quelque chose, il demande à Chuck Norris.",
	"Chuck Norris n'a pas besoin de GPS, c'est lui qui indique la direction aux satellites.",
	"Chuck Norris est le seul homme à avoir vaincu un mur de briques au pierre-papier-ciseaux.",
	"Chuck Norris peut faire cuire un œuf dur en le regardant fixement.",
	"Quand Chuck Norris fait un test de personnalité, le résultat est toujours : 'Badass'.",
	"Le Titanic ne s'est pas cogné contre un iceberg, mais contre le pied de Chuck Norris.",
	"Chuck Norris est capable de regarder l'éclipse solaire sans lunettes.",
	"Quand Chuck Norris met son lecteur mp3 en mode aléatoire, il écoute toujours la même chanson.",
	"Chuck Norris peut trouver Charlie en fermant les yeux.",
	"Chuck Norris est immunisés contre les virus informatiques",
	"Chuck Norris peut trouver un trèfle à quatre feuilles en une seconde.",
	"Chuck Norris n'a pas besoin d'ouvrir les portes, elles s'écartentd'elles-mêmes.",
	"Chuck Norris a déjà terminé une course avant même de la commencer.",
	"Chuck Norris peut manger du riz avec des baguettes... une grain à la fois.",
	"Chuck Norris peut faire des ricochets sur l'eau avec une balle de bowling.",
	"Les tornades suivent les conseils de Chuck Norris pour se déplacer.",
	"Chuck Norris peut éteindre un feu en le jetant dans l'eau.",
	"Chuck Norris est capable de courir sur l'eau.",
	"Chuck Norris sait parler aux poissons.",
	"Chuck Norris peut envoyer des SMS avec un téléphone fixe.",
	"Chuck Norris peut faire tourner le ventilateur avec sa seule respiration.",
	"Chuck Norris a déjà remporté une course de vitesse contre la lumière.",
	"Chuck Norris a déjà réussi à installer Windows sur un Mac.",
	"Quand Chuck Norris joue au Monopoly, c'est l'économie mondiale qui s'effondre.",
	"Chuck Norris peut cuire un steak en le serrant très fort dans sa main.",
	"Chuck Norris peut répondre à une question rhétorique.",
	"Chuck Norris peut arrêter le temps en regardant sa montre.",
	"Quand Chuck Norris joue au foot, il marque des essais.",
	"Chuck Norris peut prendre une photo de son ombre.",
	"Chuck Norris peut faire des squats en étant assis.",
	"Chuck Norris peut soulever une montagne avec une main.",
	"Chuck Norris sait comment on fait les bébés.",
	"Chuck Norris peut jouer au tennis contre un mur et gagner.",
	"Quand Chuck Norris se pèse, la balance affiche : 'À prendre avec des pincettes'.",
	"Chuck Norris peut faire des tractions avec un seul doigt.",
	"Chuck Norris peut jongler avec des boules de bowling enflammées.",
	"Chuck Norris connaît la dernière décimale de Pi.",
	"Chuck Norris peut plier une cuillère en la regardant.",
	"Quand Chuck Norris fait du vélo, il n'a pas besoin de pédales.",
	"Chuck Norris peut éplucher une banane avec les pieds.",
	"Les statues de cire de Chuck Norris sont en acier.",
	"Chuck Norris peut boire un verre d'eau en une seule gorgée.",
	"Chuck Norris peut faire un Rubik's Cube les yeux fermés.",
	"Chuck Norris n'a pas besoin d'oxygène pour respirer.",
	"Chuck Norris peut faire un caramel avec du sucre et de l'eau froide.",
	"Chuck Norris peut faire cuire des pâtes en moins de 8 minutes.",
	"Quand Chuck Norris joue au Scrabble, il invente des mots qui comptent triple.",
	"Chuck Norris peut jouer au badminton avec une raquette de tennis.",
	"Chuck Norris peut souffler sur un avion en papier pour le faire voler.",
	"Quand Chuck Norris joue à cache-cache, personne ne le trouve.",
	"Chuck Norris peut déchirer une feuille d'acier.",
	"Chuck Norris peut décoller une étiquette sans la déchirer.",
	"Chuck Norris connaît la recette secrète du Coca-Cola.",
	"Chuck Norris peut conduire une voiture avec un volant de vélo.",
	"Quand Chuck Norris plante des graines, elles poussent immédiatement.",
	"Chuck Norris peut lire le contenu d'un DVD en le faisant tourner sur son doigt.",
	"Chuck Norris n'a pas besoin de dormir, il cligne des yeux très lentement.",
	"Chuck Norris peut casser un œuf avec une main sans en mettre partout.",
	"Quand Chuck Norris se perd, c'est le monde qui doit se réorienter.",
	"Chuck Norris connaît la fin de l'histoire de l'œuf et de la poule.",
	"Chuck Norris peut faire du patin à glace sur du parquet.",
	"Chuck Norris peut faire le tour du monde en 80 secondes.",
	"Chuck Norris peut jouer au flipper avec une seule main.",
	"Quand Chuck Norris fait des burpees, il soulève la Terre.",
	"Chuck Norris peut monter l'Everest en tongs.",
	"Chuck Norris peut faire rire une pierre",
	"Chuck Norris peut tricoter avec des baguettes chinoises.",
	"Quand Chuck Norris met son clignotant, tout le monde change de direction.",
	"Chuck Norris peut manger des spaghettis avec une cuillère.",
	"Chuck Norris peut souffler sur une bougie allumée et l'éteindre de l'autre côté de la pièce.",
	"Chuck Norris peut jouer aux échecs contre lui-même et gagner à chaque fois.",
	"Quand Chuck Norris envoie un e-mail, il arrive instantanément.",
	"Chuck Norris peut lire un livre en le feuilletant.",
	"Chuck Norris peut éplucher une orange avec sa langue.",
	"Chuck Norris peut ouvrir une boîte de conserve avec un cure-dent.",
	"Chuck Norris peut faire du saut en parachute sans parachute.",
	"Chuck Norris peut jouer de la guitare avec ses pieds.",
	"Quand Chuck Norris prend un selfie, l'appareil photo sourit.",
	"Chuck Norris peut ouvrir une bouteille de bière avec ses paupières.",
	"Chuck Norris peut arrêter un train avec un doigt.",
	"Les plantes arrosent Chuck Norris pour grandir.",
	"Chuck Norris peut compter jusqu'à l'infini... deux fois.",
	"Chuck Norris peut dessiner un cercle parfait à main levée.",
	"Quand Chuck Norris joue au bowling, il fait un strike avec une balle de ping-pong.",
	"Chuck Norris peut réussir un examen sans jamais avoir étudié.",
	"Chuck Norris peut soulever un éléphant avec une seule main.",
	"Quand Chuck Norris entre dans une pièce, les ombres se cachent derrière lui.",
	"Chuck Norris peut mélanger du béton avec ses mains.",
	"Chuck Norris peut diviser par zéro.",
	"Quand Chuck Norris fait du surf, les requins s'écartent.",
	"Chuck Norris peut traverser un mur sans laisser de traces.",
	"Chuck Norris peut faire fondre la glace avec son regard.",
	"Quand Chuck Norris se cogne le petit orteil, c'est le meuble qui pleure.",
	"Chuck Norris peut piloter un avion avec un volant de voiture.",
	"Chuck Norris peut faire sauter des crêpes en les faisant tourner sur son doigt.",
	"Chuck Norris peut ouvrir une porte de garage sans télécommande.",
	"Les puces de parquet évitent Chuck Norris.",
	"Chuck Norris peut monter à l'envers sur un escalator qui descend.",
	"Quand Chuck Norris utilise un sèche-cheveux, il provoque des ouragans.",
	"Chuck Norris peut allumer un feu en frottant deux morceaux de glace.",
	"Chuck Norris peut mettre une étoile sur un sapin de Noël sans utiliser d'escabeau.",
	"Chuck Norris peut faire cuire un gâteau sans utiliser de four.",
	"Quand Chuck Norris fait un câlin à un ours en peluche, il devient un vrai ours.",
	"Chuck Norris peut attraper un boomerang sans qu'il revienne.",
	"Chuck Norris peut faire des bulles avec du lait.",
	"Quand Chuck Norris prend un bain, l'eau devient une source thermale.",
	"Chuck Norris peut cuire un poulet avec le frottement de ses mains.",
	"Chuck Norris peut faire sauter un bouchon de champagne avec un claquement de doigts.",
	"Quand Chuck Norris souffle sur une paille, il crée un jet d'eau.",
	"Chuck Norris peut casser une noix de coco avec sa tête.",
	"Chuck Norris peut faire tourner la Terre en sens inverse en courant à l'envers.",
	"Quand Chuck Norris utilise un parapluie, il ne pleut plus.",
	"Chuck Norris peut souffler les bougies d'un gâteau en fermant les yeux.",
	"Les oiseaux chantent pour Chuck Norris.",
	"Chuck Norris peut donner un coup de pied si puissant qu'il déplace le soleil.",
	"Chuck Norris peut marcher sur les nuages.",
	"Quand Chuck Norris utilise un marteau-piqueur, les tremblements de terre s'arrêtent.",
	"Chuck Norris peut fermer un livre ouvert sans faire de bruit.",
	"Les poissons remontent à la surface pour voir Chuck Norris nager.",
	"Chuck Norris peut changer la couleur de ses vêtements en clignant des yeux.",
	"Quand Chuck Norris marche sur la plage, le sable ne colle pas à ses pieds.",
	"Chuck Norris peut ouvrir un pot de cornichons avec son regard.",
	"Quand Chuck Norris regarde un film en accéléré, il comprend tout.",
	"Chuck Norris peut dévisser une vis avec un tournevis plat.",
	"Chuck Norris peut faire des ricochets avec un ballon de basket.",
	"Chuck Norris peut souffler des bulles avec un chewing-gum sans le mâcher.",
	"Quand Chuck Norris saute à la corde, il fait tourner la Terre autour de lui.",
	"Chuck Norris peut jouer du piano avec ses orteils.",
	"Les feux de circulation passent au vert quand Chuck Norris s'approche.",
	"Chuck Norris peut faire tourner une toupie avec son souffle.",
	"Quand Chuck Norris fait des crêpes, elles sont toujours parfaitement rondes.",
	"Chuck Norris peut attraper une mouche avec des baguettes chinoises en plein vol.",
	"Quand Chuck Norris prend un bain, l'eau se transforme en jacuzzi.",
	"Chuck Norris peut empiler des gouttes d'eau.",
	"Chuck Norris peut décapsuler une bouteille avec ses sourcils.",
	"Chuck Norris peut jouer au billard avec une queue de brosse.",
	"Quand Chuck Norris se rase, les poils tombent par terre avant que la lame ne les touche.",
	"Chuck Norris peut manger une soupe avec une fourchette.",
	"Quand Chuck Norris joue à la pétanque, il gagne avec un coup de pied.",
	"Les satellites ajustent leur position pour éviter Chuck Norris lorsqu'il saute.",
	"Chuck Norris peut faire cuire des légumes en les serrant fort dans sa main.",
	"Quand Chuck Norris prend une photo, le paysage sourit.",
	"Chuck Norris peut dévorer un sandwich en une seule bouchée.",
	"Les chiens se taisent lorsque Chuck Norris aboie.",
	"Chuck Norris peut regarder un film muet en couleurs.",
	"Quand Chuck Norris fait du yoga, il peut plier l'espace-temps.",
	"Chuck Norris peut écrire avec un stylo sans encre.",
	"Quand Chuck Norris se promène en forêt, les arbres s'écartent pour le laisser passer.",
	"Chuck Norris peut jouer au ping-pong avec un frisbee.",
	"Les moustiques préfèrent mourir de faim plutôt que de piquer Chuck Norris.",
	"Chuck Norris peut faire pleurer un oignon en le regardant fixement.",
	"Quand Chuck Norris conduit, les feux tricolores sont toujours verts pour lui.",
	"Chuck Norris peut gonfler un ballon avec un seul souffle, même s'il est percé.",
	"Les étoiles filantes font un vœu en voyant Chuck Norris.",
	"Chuck Norris peut sauter à la corde sans la faire bouger.",
	"La seul chose qui arrive à la cheville de Chuck Norris, c'est ça b*te.",
	"Chuck Norris peut peindre un tableau avec un pinceau sans poils.",
	"Quand Chuck Norris prend l'avion, il vole sans ailes.",
	"Les arbres à cames demandent l'autorisation à Chuck Norris pour tourner.",
	"Chuck Norris peut traverser un labyrinthe les yeux bandés.",
	"Quand Chuck Norris fait des pompes, il soulève la Terre.",
	"Chuck Norris peut couper du papier avec ses cils.",
	"Les feux d'artifice s'allument spontanément pour célébrer l'anniversaire de Chuck Norris.",
	"Chuck Norris peut vider une piscine en une seule gorgée.",
	"Quand Chuck Norris fait des ricochets, l'eau rebondit sur la pierre.",
	"Chuck Norris peut lire un livre en braille avec ses pieds.",
	"Les tapis roulants demandent à Chuck Norris de les faire avancer.",
	"Quand Chuck Norris commande un steak, la vache s'aplatit d'elle-même.",
	"Chuck Norris peut faire du vélo sans les roues.",
	"Les GPS demandent leur chemin à Chuck Norris.",
	"Chuck Norris peut effacer un CD avec un simple regard.",
	"Quand Chuck Norris enfile des gants, ses doigts ne touchent jamais le fond.",
	"Chuck Norris peut faire bouillir de l'eau en la mettant au congélateur.",
	"Les éclairs demandent l'autorisation à Chuck Norris avant de frapper.",
	"Chuck Norris peut souffler un vent si fort qu'il déracine les arbres.",
	"Quand Chuck Norris joue aux cartes, il gagne même sans les regarder."
};

int main() {
    srand(time(NULL));
    int index = rand() % (sizeof(blagues) / sizeof(blagues[0]));

    printf("%s\n", blagues[index]);

    return 0;
}
